apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar-deployment
  labels:
    app: bar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - name: bar
        image: mihirshirali/bar:latest
        env:
        - name: AGENT_HOSTNAME
          value: tempo
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: bar
  labels:
    app: bar
spec:
  ports:
  - port: 7074
    targetPort: 5000
    protocol: TCP
  selector:
    app: bar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-deployment
  labels:
    app: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: foo
        image: mihirshirali/foo:latest
        env:
        - name: AGENT_HOSTNAME
          value: tempo
        - name: BAR_ENDPOINT
          value: http://bar:7074/bar
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: foo
  labels:
    app: foo
spec:
  type: NodePort
  ports:
  - port: 7075
    targetPort: 5000
    protocol: TCP
  selector:
    app: foo
